namespace Fido2.Core.Ctap2;

/// <summary>CTAP error/status codes (CTAP 2.1 error response table, incl. legacy CTAP1 codes).</summary>
public enum CtapStatusCode : byte
{
    Ok = 0x00,
    Ctap1ErrInvalidCommand = 0x01,
    Ctap1ErrInvalidParameter = 0x02,
    Ctap1ErrInvalidLength = 0x03,
    Ctap1ErrInvalidSeq = 0x04,
    Ctap1ErrTimeout = 0x05,
    Ctap1ErrChannelBusy = 0x06,
    Ctap1ErrLockRequired = 0x0A,
    Ctap1ErrInvalidChannel = 0x0B,
    Ctap2ErrCborUnexpectedType = 0x11,
    Ctap2ErrInvalidCbor = 0x12,
    Ctap2ErrMissingParameter = 0x14,
    Ctap2ErrLimitExceeded = 0x15,
    Ctap2ErrUnsupportedExtension = 0x16,
    Ctap2ErrFpDatabaseFull = 0x17,
    Ctap2ErrLargeBlobStorageFull = 0x18,
    Ctap2ErrCredentialExcluded = 0x19,
    Ctap2ErrProcessing = 0x21,
    Ctap2ErrInvalidCredential = 0x22,
    Ctap2ErrUserActionPending = 0x23,
    Ctap2ErrOperationPending = 0x24,
    Ctap2ErrNoOperations = 0x25,
    Ctap2ErrUnsupportedAlgorithm = 0x26,
    Ctap2ErrOperationDenied = 0x27,
    Ctap2ErrKeyStoreFull = 0x28,
    Ctap2ErrNoOperationPending = 0x2A,
    Ctap2ErrUnsupportedOption = 0x2B,
    Ctap2ErrInvalidOption = 0x2C,
    Ctap2ErrKeepaliveCancel = 0x2D,
    Ctap2ErrNoCredentials = 0x2E,
    Ctap2ErrUserActionTimeout = 0x2F,
    Ctap2ErrNotAllowed = 0x30,
    Ctap2ErrPinInvalid = 0x31,
    Ctap2ErrPinBlocked = 0x32,
    Ctap2ErrPinAuthInvalid = 0x33,
    Ctap2ErrPinAuthBlocked = 0x34,
    Ctap2ErrPinNotSet = 0x35,
    Ctap2ErrPuatRequired = 0x36,
    Ctap2ErrPinPolicyViolation = 0x37,
    Ctap2ErrPinTokenExpired = 0x38,
    Ctap2ErrRequestTooLarge = 0x39,
    Ctap2ErrActionTimeout = 0x3A,
    Ctap2ErrUpRequired = 0x3B,
    Ctap2ErrUvBlocked = 0x3C,
    Ctap2ErrIntegrityFailure = 0x3D,
    Ctap2ErrInvalidSubcommand = 0x3E,
    Ctap2ErrUvInvalid = 0x3F,
    Ctap2ErrUnauthorizedPermission = 0x40,
    Ctap1ErrOther = 0x7F,
}
